### ISSUE TITLE
1.14.4 config update/1.15.2 update?

### ISSUE THREAD

**Issue by lAlphal** [Yesssssman/epicfightmod#1041]
Greetings mod creator!

My friends and I were planning on adding your mod to a custom modpack for 1.14.4, compromising for the fact that there isn't a version for 1.15.2

I was planning on applying your custom animations to a couple of weapons from another mod, only to discover that the 1.14.4 version of the mod does not generate/support a config yet.

Is there a possibility for updating the 1.14.4 version of the mod to support configs, or for a 1.15.2 update with config support?

Thank you for your consideration and hard work.

**Comment by MetalKnight56** [comment]
1.15.2 is not planned and will not happen any time soon. We are sorry but we have major priorities that need more attention. Since 1.15.2 isn't a major modding update we will not be supporting it. Well it could happen one day, but it will probably take some years haha, in the mean time, you can appreciate Epic Fight, in 1.16.5 and 1.18.2.

**Comment by lAlphal** [comment]
> 1.15.2 is not planned and will not happen any time soon. We are sorry but we have major priorities that need more attention. Since 1.15.2 isn't a major modding update we will not be supporting it. Well it could happen one day, but it will probably take some years haha, in the mean time, you can appreciate Epic Fight, in 1.16.5 and 1.18.2.

Thank you for the prompt response.

Though 1.15.2 will not be happening, what about config support for 1.14.4, will this be a possibility?

And again, your efforts in the creation and development of this mod are greatly appreciated.
