### ISSUE TITLE
[Suggestion] Unique first person animations

### ISSUE THREAD

**Issue by MarioSMB** [Yesssssman/epicfightmod#1127]
Currently the animations in combat mode are designed for third person combat, which is great in third person view, but they do leave a lot to be desired in first person mode;  
- Using the bow keeps it awkwardly centered in the screen making it difficult to aim. This could more or less use the vanilla animation as attacks don't seem too different
- Blocking with the guard skill often obscures the entire screen (with greatswords especially), or doesn't show the weapon at all
- Most weapons simply aren't visible from first person, the katana makes a brief appearance while swinging and even then it's obscured by the player's arm. Not to mention the hand holding the sheath covering the player's view!
- Rolling causes the player's back to be visible for a brief moment

Having a separate set of animations and such for the first person view would solve these issues and more while making first person combat far more cohesive. I hope it can be considered, thanks.

**Comment by MetalKnight56** [comment]
Compatbility between epic fight and first person model mod is already being worked on

**Comment by MarioSMB** [comment]
That's a shame to hear that a second (third if you count shoulder surfing!) mod will be required to make this mod somewhat playable, that is when the they're available. Until then it might be wise to enable third person mode automatically when switching to combat mode as it's currently incredibly difficult to play with.

**Comment by MetalKnight56** [comment]
> 

Next update should fix every issue, its just that its been decided by the team that its best to work on adding in unique features other than adding everythng to the base mod and keeping some quality of life opitional rather than enforcing them on users, so if you want these changes you'll be able to have them simply by installing these other mods which'll have built in compat, there'll still be a mssive rewrite of the current features regarding the unique first person model, but they won't be given that much attention considering there are other mods that will simply do better than us

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
