### ISSUE TITLE
[1.18.2 Forge] Incompatibility between Epic Fight and Entity Texture Features

### ISSUE THREAD

**Issue by DeadlyAccurate** [Yesssssman/epicfightmod#1150]
I don't know if anything can be done about this, but this mod stops Entity Texture Features from working (at least on Forge). ETF lets you use resourcepacks that have random texture variants (like Tissou's Zombies) without having to have Optifine installed. With both mods installed, you only get the first texture in the pack.

Forge 40.1.73
EpicFight-18.3.3-beta.jar
entity_texture_features_forge_1.18.2-4.0.2.jar

**Comment by Woodgoldtwo** [comment]
Fun fact: Entity Texture Features is open source so compatibility with it is possible
https://github.com/Traben-0/Entity_Texture_Features

**Comment by Queens21s** [comment]
i have a similar issue. I have a texture pack that changes the textures of the iron golem and the spiders (and endermen but i havent seen one after i added this mod so i dont know if they have the same problem, but probably since their animations also changed with this mod) after adding this mod their textures are completely ruined. they are see through and the textures are at the wrong part of their body n stuff. Can this be fixed?

**Comment by guivnf** [comment]
Issue was fixed way back in 20.7.1
