### ISSUE TITLE
[1.16.5] Configured Modded Weapons Still Do Vanilla Swings

### ISSUE THREAD

**Issue by UltrascatterRED** [Yesssssman/epicfightmod#116]
I have been trying to optimize compatibility between this mod and Spartan Weaponry as a pet project, and an issue I've noticed is that after I've added the Spartan weapons in the config file, when I use one of the weapons in-game, it still executes a vanilla swing that deals damage, and then it ALSO does damage from the Epic Fight swing. I confirmed that I was in combat mode, and tried fiddling with various stats in the Spartan Weaponry config file to fix this, but nothing seems to be working. Is there something I'm doing wrong, or something that needs to be fixed? Thanks.

EDIT: This is in Minecraft 1.16.5, by the way.

EDIT 2: My first assumption was that certain weapon types from the Epic Fight custom weapons config caused this problem, but that wasn't the case. I've done some further testing and concluded that the cause of this issue is actually the properties of certain weapons from Spartan Weaponry, but I'm not sure which properties. 

   Because the issue stems from Spartan Weaponry, I'm not sure how easy it would be to fix this by tweaking Epic Fight's code. I'll leave the issue open for now, but if I get a reply from @Yesssssman definitively saying that this is too hard or impossible to fix, then I'll close it.

EDIT 3: I found a link in one of the closed issue threads that shows what I'm talking about: https://streamable.com/gfwb18

**Comment by Yesssssman** [comment]
I've tested a lot of mods, but this happens only in Spartan Weaponry mod. I can't inspect the exact reason for this since they're not open source. All I can do now is leaving an option for the player to cancel all vanilla attacks. Keep watching the update note!

**Comment by UltrascatterRED** [comment]
I do not know if it would be of any help, but I now have a list of the precise weapons that cause issues:
-Greatsword
-Spear
-Pike
-Halberd
-Lance
-Glaive

From my tests, every other weapon integrates fine.

**Comment by UltrascatterRED** [comment]
Also, @Yesssssman, is this new option for vanilla attack disabling available yet? And if so, would I find it in the config files or somewhere else? Thanks.

**Comment by Yesssssman** [comment]
Yeah, I haven't made it yet. I'd make it kinda gamerule.

**Comment by darndz** [comment]
Hello! I tried update with doVanilla is False. 
In Advent of Ascension default swords working, but custom greatblades swings anyway

**Comment by Keselka** [comment]
Hi guys, its seems to be problem not only for Spartan Weaponry, also AoA3(Nevermine) have this isue (the weapon type "greatsword" keep making vanilla sweep attack), the reason of this bug is a **_long reach modificator_** function that cause weapon ignore new animations of epic fight, and we have two possible way to fix it: 1. Just wait a official fix, and make a proposal to mod creators to fix that bug. 2. Found a source code of Spartan Weaponry, and AoA3 and disable **_long reach modificator_**. If you ask me, i prefer the second method, and i make i litle progres on it, but i have troubles with the compiling code of aoa3, even whith open source code it`s not so easy to just put all pieces together, so that all.
