### ISSUE TITLE
[Bug|Crash]: The problem with animations on the server

### ISSUE THREAD

**Issue by Naarsteel** [Yesssssman/epicfightmod#1335]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

(Sorry for my English)

Good afternoon, I ran into this problem: when installing the Epic Fight-18.3.7 modification for Minecraft 1.18.2 on a third-party server, but the battle animations are not reproduced.

Forge version 40.1.80, that is, the recommended one.

I run it on the Spigot kernel, maybe this is the problem?

I have not installed any other modifications or plugins.

I attach a video of the problem.

https://github.com/Yesssssman/epicfightmod/assets/137278657/4605e936-cfd7-4f60-96b6-4ac16a04bd5b

**Comment by MetalKnight56** [comment]
This may be an issue due to the fact that you are probably using a hybrid server. If you want to make sure epic fight works, either use a plain forge server or try and contact this hybrid server developer to fix this issue for you. Please let me know if you have anything more to share, i'd be glad to help you out.
