### ISSUE TITLE
crash with ice weapons from ice and fire

### ISSUE THREAD

**Issue by R3ntora** [Yesssssman/epicfightmod#149]
i'm using the ice and fire mod and the epic fight mod for 1.16.5 and even tho i've successfully added other weapons in the config (all other weapons from the mod seem to work) every time i hit an enemy with an ice weapon or tool in fighting mode, the game instantly crashes.

to replicate, simply use an ice dragonsteel weapon added or not in the config in any way, and hit a mob in fight mode

here's my log
[latest.log](https://github.com/Yesssssman/epicfightmod/files/6255319/latest.log)

**Comment by Yesssssman** [comment]
Is this the condition you're saying? I've tried to cause a crash in the situation you're talking about, but it works fine.

https://user-images.githubusercontent.com/79469058/113556112-f489bd00-9636-11eb-8fb9-7b8c89839eb0.mp4

**Comment by R3ntora** [comment]
I've recorded it, the error in the log is stil the same, i also have some other mods but i've tried launching minecraft with only ice and fire, citadel and epic fight and the issue is still the same 


https://user-images.githubusercontent.com/81931199/113603718-4704b280-9612-11eb-8343-38894e5a88a2.mp4

all the other items work fine, but any ice tool makes my game crash

**Comment by Yesssssman** [comment]
I notice that the last part of the stacktrace indicates it occurs from iceandfire code. I've tried to search for the reason for the crash on his GitHub code but I can't figure out the reason because some codes are unavailable. Could you post this crash report there? They also can look at my code and maybe can find the reason for this problem.

![image](https://user-images.githubusercontent.com/79469058/113616850-97225a00-9690-11eb-8ed7-45ad21983ec9.png)
