### ISSUE TITLE
[Bug|Crash]: Double jump instantly disconnects from the game.

### ISSUE THREAD

**Issue by UnsexSituation** [Yesssssman/epicfightmod#1530]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

![image](https://github.com/Yesssssman/epicfightmod/assets/142322498/a4804f95-9330-4174-9d13-341bef439344)

**Comment by MetalKnight56** [comment]
Do you have weapons of miracles?

**Comment by UnsexSituation** [comment]
No, I don't.

**Comment by MetalKnight56** [comment]
> No, I don't.

Attach your logs

**Comment by UnsexSituation** [comment]
https://mclo.gs/YTrxsyJ

**Comment by MetalKnight56** [comment]
> https://mclo.gs/YTrxsyJ

You just have so many mods and they are outputing so many errors at the same time too, its  very hard to figure out the problem yk. First of all, try to remove all mods except epic fight and make sure that the problem does not happen when only epic fight is enabled. After that, you can add the other epic fight addons you have (make sure to always test things until you get the crash), and after that you can then slowly re add mods one by one until you find the culprit. In any case, you have many mods that are conflicting/do the exact same thing like, CustomSkinLoader and Offline Skins, or a bunch of different mcreator mods (which most likely can cause issues too)

Like : the Dungeons content mod, and a bunch of different create addons (which most likely some may be conflicting with each too)
Not to mention the huge ammount of rubidium/oculus/embedium addons that may as well impact on your modpack too...

So yeah, can't help you without you debbuging and finding the culprit yourself, again, this is 100% a mod incompatibility, and most likely is happening due to the sheer ammount of conflicting mods. Best guess would be to remove them all and slowly re add them... 

You have 121 errors like just fix them omfg
