### ISSUE TITLE
[Bug|Crash]: Server crash on startup

### ISSUE THREAD

**Issue by Skyriskz** [Yesssssman/epicfightmod#1544]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

https://paste.gg/p/anonymous/e94b47de299d4a3cb7c0adf7e9af302e

the error code I receive when I start my server.

**Comment by hyqzaa** [comment]
Hello, I'm here again. I'm the one who found some of the weapon type damage Bump box decision bugs. My integration package is not online, I have been checking this bug for three days, found that it is "epic fight" problem, feel this bug is so strange. Hello, I'm here again. I'm the one who found some of the weapon type damage Bump box decision bugs. My integration package is not online, I have been checking this bug for three days, found that it is "epic fight" problem, feel this bug is so strange. Version 19.5.24 of 1.19.2 used [limited time, I didn't test other versions of the game]. Any time you use any of the "epic fight" packets on the bio side, it will result in a loss of connection and a message like "Invalid player data" will be displayed. Even if the homeowner uninstalls the relevant packet without exiting the game and opens the connection after entering the world, the same bug will still appear, unless you uninstall the packet and then both sides completely shut down the game and restart the bug will not trigger [my English is not good, I can only use translation dialogue]. Version 19.5.24 of 1.19.2 used [limited time, I didn't test other versions of the game]. Any time you use any of the "epic fight" packets on the bio side, it will result in a loss of connection and a message like "Invalid player data" will be displayed. Even if the homeowner uninstalls the relevant packet without exiting the game and opens the connection after entering the world, the same bug will still appear, unless you uninstall the packet and then both sides completely shut down the game and restart the bug will not trigger [my English is not good, I can only use translation dialogue].

**Comment by MetalKnight56** [comment]
> the error code I receive when I start my server.
Update the mod/ remove modern fix.
