### ISSUE TITLE
[Bug|Crash]: ArmorStand

### ISSUE THREAD

**Issue by OneWorldStudio** [Yesssssman/epicfightmod#1795]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

the same thing happens with Sodiun+iris Forge and Embeddium + Oculus when creating armor

### Steps to Reproduce

I don't know

**Comment by OneWorldStudio** [comment]
[crash-2024-09-02_07.56.27-client.txt](https://github.com/user-attachments/files/16832422/crash-2024-09-02_07.56.27-client.txt)

**Comment by guivnf** [comment]
Provide footage of the issue and how to replicate it

**Comment by OneWorldStudio** [comment]
> [crash-2024-09-02_07.56.27-client.txt](https://github.com/user-attachments/files/16832422/crash-2024-09-02_07.56.27-client.txt)

![image](https://github.com/user-attachments/assets/74d0e80b-3ead-4121-a397-669bd63052be)

https://drive.google.com/file/d/1b0j7SFZeKSdthdCmJpsC0oxY2ezsOnD5/view?usp=sharing

**Comment by guivnf** [comment]
Read the support policy before reporting anything with sinytra connector.

**Comment by OneWorldStudio** [comment]
> Прежде чем сообщать о чем-либо с помощью sinytra connector, ознакомьтесь с политикой поддержки.
Понятно, надеюсь ваш мод будет в дальнейшем провальный, а так я еще специально портирую ваш мод на названые версии и ниже и Fabric и случайно укажу ваш дискорд поддержки))))))

**Comment by devvywev** [comment]
@MetalKnight56 I hope you realize 95% of people would choose Sinytra Connector (and all the fabric mods it brings) any day over your mod. You aren't doing yourself any favors by trying to ignore it's existence, especially when the issue has more to do with Epic Fight than Connector.

**Comment by GLMaster19** [comment]
> > Прежде чем сообщать о чем-либо с помощью sinytra connector, ознакомьтесь с политикой поддержки.
> > Понятно, надеюсь ваш мод будет в дальнейшем провальный, а так я еще специально портирую ваш мод на названые версии и ниже и Fabric и случайно укажу ваш дискорд поддержки))))))

Чел, тебе ничего не стоит просто убрать Синитру из своего списка модов и проверить, крашит с ним или нет.
Мод сам по себе довольно конфликтный, хоть у меня он не вызывает никаких проблем. У него много моментов, из-за которых его стоит убрать просто чтобы понять, крашит из-за него или из-за самого мода. Ты даже если откроешь crashLog, то увидишь надпись про Синитру от его же создателя:
"Прежде чем составлять отчёт о конфликте про другой мод, убедитесь, что проблема не в Синитре".
Убери мод из папки с модами и пересоздай репорт здесь. В чем проблема?

**Comment by GLMaster19** [comment]
> @MetalKnight56 I hope you realize 95% of people would choose Sinytra Connector (and all the fabric mods it brings) any day over your mod. You aren't doing yourself any favors by trying to ignore it's existence, especially when the issue has more to do with Epic Fight than Connector.

Actually, Synitra itself is conflicted, because of this you should first remove this mod from your mods list to be completely sure that it's not the problem.
There's even a note about this mod from its own creator in the crash reports that appears when you start the world and get a crash. Read it.
If Sinytra is the problem, you have to go directly to its creators after checking, and the chance that this mod is the problem is pretty high. That's why they tell you to remove it to rule out that the problem is Sinytra - to be 100% sure that the issue is with EF.

**Comment by guivnf** [comment]
> > Прежде чем сообщать о чем-либо с помощью sinytra connector, ознакомьтесь с политикой поддержки.
> 
> Понятно, надеюсь ваш мод будет в дальнейшем провальный, а так я еще специально портирую ваш мод на названые версии и ниже и Fabric и случайно укажу ваш дискорд поддержки))))))
> 
> 

Oh I don't care, all assets used are under ARR license meaning you have to re animate it all otherwise I'll send a cease and desist letter to your fork page on GitHub. It's not my problem you are incompetent and don't read our support policy before reporting, sinytra is very intrusive and breaks a lot of things, and when we got into forge we had no plans of supporting fabric mods and forge mods in a "hybrid" environment. If you want fabric mods go to fabric or deal with the consequences of an imperfect bridge.

**Comment by guivnf** [comment]
> @MetalKnight56 I hope you realize 95% of people would choose Sinytra Connector (and all the fabric mods it brings) any day over your mod. You aren't doing yourself any favors by trying to ignore it's existence, especially when the issue has more to do with Epic Fight than Connector.

Who are you again? Sorry I don't really care whatever you are saying, our mod works just fine on forge and it's not our problem you are trying to temper with mods that weren't built for forge. Yet you still report issues to us as if the problem resides within our mod. Learn some Java and modding and port whatever mods you want to forge instead of relying in a tool you clearly ain't smart enough to use

**Comment by guivnf** [comment]
> > > Прежде чем сообщать о чем-либо с помощью sinytra connector, ознакомьтесь с политикой поддержки.
> 
> > > Понятно, надеюсь ваш мод будет в дальнейшем провальный, а так я еще специально портирую ваш мод на названые версии и ниже и Fabric и случайно укажу ваш дискорд поддержки))))))
> 
> 
> 
> Чел, тебе ничего не стоит просто убрать Синитру из своего списка модов и проверить, крашит с ним или нет.
> 
> Мод сам по себе довольно конфликтный, хоть у меня он не вызывает никаких проблем. У него много моментов, из-за которых его стоит убрать просто чтобы понять, крашит из-за него или из-за самого мода. Ты даже если откроешь crashLog, то увидишь надпись про Синитру от его же создателя:
> 
> "Прежде чем составлять отчёт о конфликте про другой мод, убедитесь, что проблема не в Синитре".
> 
> Убери мод из папки с модами и пересоздай репорт здесь. В чем проблема?

 Thanks for your support, it's quite hard sometimes having to deal with people like this.
