### ISSUE TITLE
Desert exception ticking world  

### ISSUE THREAD

**Issue by Yargenshmoler** [Yesssssman/epicfightmod#288]
#171, #72, and #64 are about this and I seem to have narrowed it down to a hostile mob in the desert that is trying to be spawned  but running into an issue. further testing reveals that husks do not spawn when spawned with an egg either but make their noise, which leads me to believe that in some way husks spawning is what's crashing the game. not exactly a coder though, just trying to make an educated guess.
[crash-2021-06-08_22.44.09-server.txt](https://github.com/Yesssssman/epicfightmod/files/6621054/crash-2021-06-08_22.44.09-server.txt)

**Comment by Coraline77447** [comment]
When I was experiencing the "java 84" (my nickname for that specific issue) in the logs that I see java 84 in it that says "zombie" which the husk is a type of zombie and most times when I did experienced that specific problem was when I was either in a desert biome or close to one.

"_at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.**Zombie**Data.initAttributes(**Zombie**Data.java:58) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.onEntityJoinWorld(LivingData.java:72) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.MobData.onEntityJoinWorld(MobData.java:44) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.**Zombie**Data.onEntityJoinWorld(**Zombie**Data.java:29) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.**Zombie**Data.onEntityJoinWorld(**Zombie**Data.java:22) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents**.spawnEvent**(EntityEvents.java:76) ~[epicfight:1.0] {re:classloading}_"

But what's causing "java 82" to trigger an exception? Which was the last issue that I'd finally ran into before I'd stopped playing with EFM cause I'd gotten so fed up with EFM's issues and now I'm waiting for these issues to be resolved before I would ever consider coming back to EFM (especially with gun mods)
Also I'm starting to see a pattern with "java 85" which is the ASM Event Handler (ASMEventHandler) for nearly all related crashes with EFM which my first crash from EFM was about the player as of attributes to the player at java 85 then moved onto other entities other than the player at java 85. Even tho java 85 doesn't relate to the main issue which is java 84 and java 82. 

Whatever EFM is doing at java lines 84 and 82 it's not supposed to be doing whatever it's currently doing which both the game and forge aren't agreeing with those modifications that EFM is doing to those pieces of code which is screwing up husk spawns as of java 84 but I don't know what java 82 is and what EFM is doing in java 82 to cause an exception to be thrown.
So basically the owner of EFM may have to rewrite those pieces of code in java 84 and java 82 in order to stop those exceptions from being thrown/triggered which causes the game to crash in the first place.
To be honest I think since there's a crap ton of problems with EFM it may need a rewrite entirely cause as I see it in the issues tap on here that its a hot mess of a mod right now. 
As cool and awesome as it is on the bright side for gameplay and such but as for the technical/mechanical side of this mod is dark and gloomy with one too many problems cause of how minecraft was made/coded and how forge was made/coded which both can't handle this mod to the mod's full potential since Notch originally didn't want minecraft to be like this at all. 

As I've said in my post (Ticking Player Crash(s) #64) that I'm not dissing EFM at all since I'm just stating my opinion about Epic Fight Mod, it's concept of a different combat system than the messed up vanilla combat system (1.9 update) is cool and all but just take one good look at the issue tracker lately then you shall see what I'm sayin as for the technical/mechanical side of EFM that it might potentially mess up the game even more with a different and custom/modified combat system.
