### ISSUE TITLE
How do I create custom weaponry?

### ISSUE THREAD

**Issue by S1mpleM0use** [Yesssssman/epicfightmod#31]
How do I create custom weaponry? I do not understand it. I got into the config file, added an entry, but nothing changes after the restart.

**Comment by Yesssssman** [comment]
https://www.curseforge.com/minecraft/customization/epic-fight-spartan-weaponry
Here is an example of custom weaponry setting with spartan-weaponry mod.

**Comment by Aopoxl** [comment]
> https://www.curseforge.com/minecraft/customization/epic-fight-spartan-weaponry
> Here is an example of custom weaponry setting with spartan-weaponry mod.

There's an issue when using this config, the custom spear and longsword weapons will still use the vanilla combat system along with the epic fight system. I don't know if this is an issue caused by the setting itself or the author of the config.

I couldn't attach a video demonstrating it but here is a link
https://streamable.com/gfwb18
