### ISSUE TITLE
Random textures optifine

### ISSUE THREAD

**Issue by BruhPotato420** [Yesssssman/epicfightmod#370]
When using an optifine resource pack that has randomized mob textures the game doesnt use them and only uses default textures.

**Comment by XanTheMann** [comment]
I'm not a dev, but I'll give my best judgement. The mod adds custom animations to most hostile vanilla mobs and changes the location and movement of all body parts so maybe the new textures from your resource pack aren't connecting properly because they are meant for the standard vanilla animations. Or the resource pack is just outdated.
