### ISSUE TITLE
[Question/Suggestion] RenderPlayerEvent instead of RenderLivingEvent

### ISSUE THREAD

**Issue by Cheaterpaul** [Yesssssman/epicfightmod#372]
You are using the RenderLivingEvent
https://github.com/Yesssssman/epicfightmod/blob/066bda4008a17a9d050587813ef27595ccf8edf9/main/java/maninhouse/epicfight/client/events/engine/RenderEngine.java#L320
to replace the players model rendering with yours. My question would be why you don't use the `RenderPlayerEvent.Pre` that is fired in `PlayerRenderer#render` and thus is only fired for `ClientPlayerEntitie`s. 

I am asking because my mod werewolves sometimes replaces the player model with a werewolf renderer that still extends `LivingRenderer` which causes Epic Fight Mod to cancel the event.

**Comment by Yesssssman** [comment]
I can't render any of the none player entities with RenderPlayerEvent. It only fired when the player is rendered (both ClientPlayerEntity and RemoteClientPlayerEntity). And RenderLivingEvent also includes RenderPlayerEvent because the PlayererRenderer calls the super method LivingRenderer#render. I don't have any reason to use RenderPlayerEvent.
