### ISSUE TITLE
Pretty much all weapons gone

### ISSUE THREAD

**Issue by Elyargon** [Yesssssman/epicfightmod#478]
I just woke up this morning and i checked my modpack.
"oh, a new update on Epic Fight mod"
I updated and all weapons were gone. There was just katana, one greatsword and all spears up to diamond.
I got really sad beacaause I was on the way to make a mod that fits perfect with epic fight mod.
Can somebody please tell me why this happened.

**Comment by Yesssssman** [comment]
You mean, you can't find them on the creative tab? or just disappeared from the inventory?

**Comment by TripConeHead** [comment]
curseforge broke epicfight on their app, for a while it just straight up vanished, for a few hours it was back but only on a version from half a year ago, now it's gone again. they can't fix it right now seemingly because their servers are dying and / or they're getting ddosed. if you're only playing singleplayer you can download the latest alpha version from curseforge but their webstie seems to be down so that might not be possible.

**Comment by Elyargon** [comment]
Thanks, I used the curseforge app but now I am going to try it with the website and hope it should work. A mod as good as this is hard to find.
