### ISSUE TITLE
[Suggestion] about combat mode

### ISSUE THREAD

**Issue by thunderbear06** [Yesssssman/epicfightmod#61]
I think it would be a whole lot better if combat mode was turned on when a player holds a weapon rather than by pressing a button and then turns off when there not holding a weapon, yeah that's it otherwise amazing mod Mojang should take notes

**Comment by Yesssssman** [comment]
I've considered that issue a lot, Let me give you an example.  The axe is a type of weapon in this mode. But what if you were holding an ax for logging? Since mining block is forbidden in combat mode, the axe will be recognized as a weapon and you will not be able to cut the tree the moment you're switched to combat mode. That's why I made a distinction between combat mode and mining mode. If you can't still be satisfied, I can make an option that exhibiting the vanilla fight.

**Comment by thunderbear06** [comment]
Ah i see, i didn't think about that

**Comment by JollyBrolly** [comment]
> I've considered that issue a lot, Let me give you an example. The axe is a type of weapon in this mode. But what if you were holding an ax for logging? Since mining block is forbidden in combat mode, the axe will be recognized as a weapon and you will not be able to cut the tree the moment you're switched to combat mode. That's why I made a distinction between combat mode and mining mode. If you can't still be satisfied, I can make an option that exhibiting the vanilla fight.

I was about to suggest the same thing. Is it possible to add auto switch mode for any weapon exept axe?
