### ISSUE TITLE
Shaders remove textures

### ISSUE THREAD

**Issue by Avaloneon23** [Yesssssman/epicfightmod#63]
Only tried it with two different shaders, specifically the chocapic13_v9.1_Extreme_beta_5 and Slidurs Vibrant Shaders Lite v1.283. The textures of the models went missing after applying the shaders to the game.

**Comment by Avaloneon23** [comment]
My launcher won't allow me to update forge 'til the launcher itself updates, so maybe you could check it yourself if it won't be a hassle? MC version is 1.16.5 btw

**Comment by Yesssssman** [comment]
I've already tested it and it just works fine with me.
https://www.youtube.com/watch?v=ov4Xk_SOans

There's a conflict between the Forge and Optifine mod in some versions. It's better to update both of them. If there're still problems with you, Remove my mod and check the problem is gone then report me again.

**Comment by Avaloneon23** [comment]
Even the weapon models you made? That was what I was missing which I forgot to mention lol.

But even so, yeah it may be because of my outdated versions, so I'll wait until then when the launcher I use updates. I'll come back to it once it does.

**Comment by Avaloneon23** [comment]
I was able to update Forge and Optifine now, the models for the greatsword, katana, and spears are still missing with the shaders.

**Comment by Yesssssman** [comment]
I had the same problem, but when I restarted the game, It solved. Won't you try it?

**Comment by Valen62142** [comment]
I have the same problem with BSL and Sildurs shaders
