### ISSUE TITLE
Slight incompatibility with cosmetic armor reworked (Low Priority)

### ISSUE THREAD

**Issue by Coach-mdl** [Yesssssman/epicfightmod#644]
Armor equipped in vanity slots does not show up in first person during combat mode. Instead the armor you are wearing in your regular armor slots will render.

**Comment by gaesyeah** [comment]
Hi. @Coach-mdl maybe you can try to talk about this with the devs of the "cosmetic armor reworked".

**Comment by gaesyeah** [comment]
oh i got it, have sense. Thanks.

**Comment by zlainsama** [comment]
my mod works by replacing items right before rendering a player and restoring them after. ([it uses RenderPlayerEvent.Pre and RenderPlayerEvent.Post](https://github.com/zlainsama/CosmeticArmorReworked/blob/538959ce1e0dbf81da9f14bcb11ade5f0bc3efa7/src/main/java/lain/mods/cos/impl/client/PlayerRenderHandler.java))
if your renderer could implement these render events, then compatibility should be able to achieve.
otherwise, if you could provide a special render event similarly for your renderer, I can add compatibility code on my side.

**Comment by gaesyeah** [comment]
Hi, thanks @zlainsama, but @Yesssssman apparently is only going to come back in October 27th due to personal reasons: https://github.com/Yesssssman/epicfightmod/issues/662

**Comment by Yesssssman** [comment]
@zlainsama Hello, I have a question about how to access your code. Since I'm a beginner at modding, I thought I had to add a dependency to access your code. But in this case, I think that people need to install your mod to run Epic Fight. But If I misunderstood, Is there any way to detect if your mod is installed in runtime? so that it doesn't have to run the code that checks the vanity slot if your mod is not installed.

**Comment by zlainsama** [comment]
@Yesssssman I finally played EpicFight myself, and I know the problem now, I will release a fix in 1.16.5 and 1.17.1 on my end.

**Comment by Yesssssman** [comment]
Oh, I nearly forgot about this issue... sorry and thanks for your time.

**Comment by Yesssssman** [comment]
Actually, In my last attempt, I failed to build the project that was dependent on your mod.
