### ISSUE TITLE
Custom textures on vanilla armor and Tissou's Zombie Pack

### ISSUE THREAD

**Issue by Avaloneon23** [Yesssssman/epicfightmod#67]
Hey, it's me again,

I'm using Kal's Arms and Armor which allows me to use different models of armor by renaming it to heavy or light variants. When being in 3rd person, it shows the default variant rather than the unique other variants no matter what I do.

Also with Tissou's Zombie Pack, which has random zombie models it only shows one type of model and not its other variants.

Custom Items, Custom Mob Models, and Random Models are on when I tested it, but again, I'm still using the outdated versions of forge and Optifine so I can't be to sure. But if it does still do the same thing even with the updated versions, I thought I might as well say it now.

Again, sorry as I can't test it out properly with my forge and Optifine versions lol

**Comment by Avaloneon23** [comment]
I tested it out with the latest versions of forge and optifine, I got similar results too.

**Comment by ClockworkzAI** [comment]
"I'm using **Kal's Arms and Armor** which allows me to use different models of Armor by renaming it to heavy or light variants. When being in 3rd person, it shows the default variant rather than the unique other variants no matter what I do." 

1.16.5.9 
using forge 36.2.4

The same problem with this resource pack, is there way to change it thru the config or is it not possible?
