### ISSUE TITLE
Armor dissapering when going into battle mode

### ISSUE THREAD

**Issue by Maffinn** [Yesssssman/epicfightmod#707]
So i installed the new version of epic fight mod released, and now armor doesnt show when i go into battle mode, it becomes invisible, also some swords arent in the hand properly, the greatsword from spartan armory is behind the hands, completly diffrent from the previous update

**Comment by Maffinn** [comment]
Also it doesnt auto configure mods like spartan weaponry, every weapon is a normal sword with this new version, i tested the 5,1.5 version and it auto configured the weapons to work like a greatsword axe etc, also ther 5.1.5 version crashes the game when equiping anything into the off hand

**Comment by Yesssssman** [comment]
In the update log of 5.1.6,

>Vanilla tools and weapons from other mods are automatically registered as they did in versions below 5.1.0.

It only can set the "Vanilla" weapons like Sword, Axe, Pickaxe, Hoe, Shovel. All spartan weaponry weapons you've mentioned basically have the data structure of Sword in vanilla, so the system recognizes them as Sword. In this situation, you have to set a configuration file or datapack. 

Also, I guess you've installed Wizard Staff mod. Those are incompatible for now because Wizard Staff uses a different system to draw a holding weapon.

Last, the crash when swapping the offhand was fixed in the 5.1.6 version. Please update your mod file.

**Comment by Maffinn** [comment]
I cant use the newest version as for me its broken, the armor is invisible while in battle mode, i dont have any wizard mod installed, vanilla armor or modded just becomes invisible while in that mode, how to fix this?

**Comment by Yesssssman** [comment]
Hello, I'm pretty sure that this problem was related to #711. Could you test if this issue is solved in latest version?
