### ISSUE TITLE
[Suggestion & Bug] Config values & Swing bug

### ISSUE THREAD

**Issue by Shikomi36** [Yesssssman/epicfightmod#736]
Please add more values for custom weapons. Maybe something for swing speed and reach, whenever I add a custom weapon it always has a set value which makes them swing really slow in servers. And if it has a big model it becomes hard to land hits on mobs/players.

As for the bug I've noticed that when I swing with certain custom weapons the slash from the normal Minecraft combat comes out before the epic fight one does. I don't know if this is intended or not so I'm just going to bring attention to it.

Here is a video of the bug in a single player world.
The weapons in the video are set as swords in the config.
https://streamable.com/kwlirg

**Comment by Keselka** [comment]
Oh sh%t, seem's that the the "vanilla swing problem" is just ignores by developer
So i have the same issue on the AoA3 mod, the weapon type "greatblade" and "hammer" have that "vanilla sweep attack" i think it's because of a "attack_reach_modifier" that calculates above the base attack reach, but i don't sure of it.
