### ISSUE TITLE
Compatability request: allow for Regenration animation to play while in combat mode when triggured

### ISSUE THREAD

**Issue by Shibva** [Yesssssman/epicfightmod#763]
for details please refer to this issue posted on their end

https://github.com/Suff99/Regeneration/issues/336

I hope this can be fixed somehow, this mod is open sourced so I think it might be possible

**Comment by SteamDoge9000** [comment]
in fact nevermind, I think this was fixed by you or something

**Comment by SteamDoge9000** [comment]
in fact, there is one thing that I would like to request, when you die the rengeration thing will not play as it should when you in combat mode (extend arms out)

and while it may raise problems to have it disable combat mode when dying, I have a suggestion

since the mod is open source, if the mod (eplc fight) detects a regeneration, then it will disable the custom render while the regeneation animation goes on (this last from regeneration to post regen, where the special animation stops)
