### ISSUE TITLE
[Suggestion] Modded Mobs Compatibility

### ISSUE THREAD

**Issue by InteJason** [Yesssssman/epicfightmod#79]
I've gotten a lot of requests to put this mod in my modpack, but since modded mobs don't stun or get stunned, it's kind of unbalanced. Will there be modded creature compatibility coming in the near future (though i understand how difficult it can be)

**Comment by Yesssssman** [comment]
Hmm.. I think it's possible to make compatibility with monsters who have the same model as vanilla,  but the problem is mobs with the custom models (like custom armor). They would not work properly.

**Comment by hitmanssilent** [comment]
I have an idea, do not add animations for the hostile mobs of other mods, there may be three options, the first is to make all the mobs of other mods are affected by a knockback effect even if the weapon is not enchanted (and if the weapon is enchanted with this effect, which only takes effect from level two of the enchantment) because for example I have put an enchantment effect to a great sword of the spartan weaponry mod and the truth is that combat with mods mobs is makes it more fair, another thing that could be done is to add by default an attack recharge time for the mobs of other mods based on the damage it can cause to the player, the more damage it causes, logically the longer it will take to reload the attack, the third option is a mixture of both but with a configuration file in which we can add the mobs of the mods that we want by applying the parameters of attack time and push that we want it to have when the player attacks.

**Comment by Yesssssman** [comment]
Well, to complish that, I have to redesign the monster's AI. but it's impossible if they're patched with a custom AI. (this means, if they're using their mod's own AI, I can remove them cause there's no way to recognize and remove it) in my opinion, I can make it compatible only with mobs that have the vanilla minecraft's AI code and have the model that equal to vanilla minecraft

**Comment by InteJason** [comment]
Or maybe disable a mob’s a.i. temporarily when a mob gets hit (to simulate “stunning”)? Would that work?

Also there’s the problem with player not getting stunned by modded mobs

**Comment by hitmanssilent** [comment]
Nah, it's not that easy, he's right, in order to temporarily deactivate the AI of some enemy he would have to do it specifically for each mod that exists, because not all have a unified way of creating an AI. Still, the easiest thing might be to implement knockback when hitting a mob, right? After all, regardless of which mod is used, all mobs are affected by the knockback effect.
