### ISSUE TITLE
Greatswords from other mods (Spartan Weaponry) still do the vanilla attack (sweep attack) as well as the custom greatsword attack.

### ISSUE THREAD

**Issue by elidhan** [Yesssssman/epicfightmod#814]
I edited the mod's config file to include Spartan Weaponry's weapons. The greatswords, I set as, greatswords in the config and for the most part it works fine except that when in battle mode, it does the vanilla sweep attack on top of the mod's custom attack animation.

**Comment by lyeochan** [comment]
pretty sure u have to disable the vanilla atack on the gamerule when creating a world

**Comment by DarkScorn** [comment]
You have to edit weapon types in epic fight config. Yessman has a video guide on how to edit the config file. There is no bug or issue.

**Comment by Keselka** [comment]
Have the same issue on AoA3 mod too, after some long researche i find out that problem is in the "attack_distance_modifier" that is not calculating by the Epic Fight Mod. I'm trying to fix that (for personal use of course) by week, but i'm newbie in java so problem seems to be serious :)
By the way, i have a little chat with the Tslat (the developer of AoA3) and he answer me that EpicFightMod cause many bug's on many mod, so he don't want to make changes in AoA3 for some sort of a compabilitie, because it's required a fundamental balanse change, so i think fix will be not soon :(
P.S. If you somewhat fix that problem, please contact with me (my gmail keselka3@gmail.com)
