### ISSUE TITLE
Mod Customization Ideas

### ISSUE THREAD

**Issue by Augusto2103** [Yesssssman/epicfightmod#896]
So I've got some customization ideas that I believe could improve this really cool mod.
- **Config File for: Stamina** (How much is used on a specific skill or if there even is stamina, just for more gameplay variety)
-  **Amount of skills possible to have at the same time** (Maybe skills would collide with eachother, so roll and step would have different keybinds) 
- **Hud Customization** (Maybe colors for different stages of the stamina, and maybe if the stamina could even change depending on how much stamina there is, enemy health bars that can show: percentage of enemies health / health points / hearts and total hearts) 
- **1st Person Improvement** (I feel like 1st person doesn't look as good, like if the weapons are way to close to the players face and it looks odd, so maybe you could change the players camera position, and maybe if the player's body would show and only the weapon) 
- **Ingame Animation Selector** (Basically you can choose an item's animation whenever they're holding 1 or 2 of the same or different, like, for some reason, I want to make it so a stick has a sword animation, but if I have 2 sticks in both hands, I have the double dagger animations, or I have 1 sword with a normal sword animation, but when I have a shield, it uses the spear + shield animation. Same for entities, you can choose what animations they use for any actions, whether it's walking, running, attacking or, if it comes in a "big update", dodging. This idea would basically be an ingame config of the one in the config. folder)

**Comment by Aronforester** [comment]
Bruh the third one is already there and u can use Toro health for the heart thing and the second one is dumb because he's trying to make everything balanced even tho that would be cool/interesting it would be kinda game breaking in pvp and for the last one u basically asking him to allow all the mobs as of now to be able to use each other's animation which would already cause so many bugs and crashes but then when the creator decides to add more mobs it's gonna be harder cus he has to add compatability between animations

**Comment by Aronforester** [comment]
Bruh I ain't arguing with u and I didn't talk about the other ones because they seemed like pretty cool advancements to the mod but still could cause problems but u really do need to put feature/suggestion when u actually ask for something to be added and I really can't bother to type long intricate messages like this unless I'm asking about features so that's why and I didn't give thoughts that weren't my main ones to your ideas cuz that would take forever but if u had discord or whatsapp we could be able to talk about other features.

P.S; I never said u were dumb
