### ISSUE TITLE
Vanilla attacks occur before swinging a weapon

### ISSUE THREAD

**Issue by yangberdo** [Yesssssman/epicfightmod#992]
Hi all, I noticed this issue whereby some weapons from other mods which utilizes the 'axe' , 'longsword' , 'greatsword' and 'spear' weapon mechanics, damages the mob before the weapon is being swung at them, this problem can be fixed by turning vanilla attacks off but for people who dont want to turn it off, is it possible to fix this issue

 The weapons mod i use is Epic Knights by Magistu, and previously in 1.16.5, i used spartans weaponry which also faces the same issue when the mob takes damage first before the swing. Hope you can look into this issue :) Thanks

**Comment by yangberdo** [comment]
Hi all, will this issue be worked on?

**Comment by Yesssssman** [comment]
Yes, but I'd work on the 1.18.2 first

**Comment by yangberdo** [comment]
The thing is, i am playing the 1.18.2 version HAHA

**Comment by MetalKnight56** [comment]
Your issue will certainly be worked on, but the thing is you'll have to wait for that to happen. Rushing him won't be of any good both for you and for him, we apreciatte your report and if we need any further information we will sure ask you. On the mean time, you will have to wait just like any other issue, when the issue gets the *working* tag, you'll know when this issue is beeing worked on. Once it's fixxed, we will notify in which version it was fixxed and we will close this report. 
Thanks for your patience.

**Comment by yangberdo** [comment]
yup no rush
